### ISSUE TITLE
Driver [meli] not supported. es MELI?

### ISSUE THREAD

**Issue by price2b** [Altivium/MeliSocialite#1]
gracias por compartir la libreria. En el foro de Mercadolibre comentaron sobre este paquete. lo instale y en el controlador ingrese el siguiente codigo:

```
        $user = Socialite::driver('meli')->user();

// OAuth Two Providers
        $token = $user->token;
        $refreshToken = $user->refreshToken; // not always provided
        $expiresIn = $user->expiresIn;

// OAuth One Providers
        $token = $user->token;
        $tokenSecret = $user->tokenSecret;

// All Providers
        $user->getId();
        $user->getNickname();
        $user->getName();
        $user->getEmail();
        $user->getAvatar();
    }
```

el error que aparece es Driver [meli] not supported. Quisiera saber si:
- el nombre de driver es meli?
- en eventserviceprovider hay que poner algun dato? ejemplo:             'SocialiteProviders\meli\......@handle',
- debo dejar en app.php (        
         Laravel\Socialite\SocialiteServiceProvider::class,
        \SocialiteProviders\Manager\ServiceProvider::class,

muchas gracias por las aclaraciones.

**Comment by silexaltivium** [comment]
Hola se debe registrar automaticamente por si no lo tienes el Service Provider del paquete

Altivium\\MeliSocialite\\MeliSocialiteServiceProvider
